name: dataanalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - colorama
  - git
  - gitdb
  - gitpython
  - h5py
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - matplotlib
  - numpy
  - nodejs
  - pandas
  - pip
  - pyarrow==1.0.1
  - pytables
  - pyyaml
  - regex
  - scipy
  - scikit-learn
  - seaborn
  - six
  - smmap
  - sqlalchemy
  - xlrd
  - tqdm

