name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - plotly 
  - tqdm
  - literal_eval
  - scikit_learn
  - tensorflow
  - tensorflow_addons 
  - wordcloud
  - Image
  - matplotlib
  - regex
  - ipywidgets 
