name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - plotly 
  - tqdm
  - ast
  - sklearn
  - tensorflow
  - tensorflow_addons 
  - wordcloud
  - PIL
  - matplotlib
  - re
  - ipywidgets 
